import 'package:flutter_project/youtube/data/model/thumb.dart';

class ThumbRepository{
  List<ThumbModel> getThumbList(){
    return [
      ThumbModel(thumbImagePath: "https://i.ytimg.com/vi/glpmn0BBhXk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC5Js6J-UgM5ntp76hAQKAMsqJw3w", userImagePath: "https://yt3.googleusercontent.com/jkm624eun6qpKa0i7PtIXYGBl-hiFHYmjvyYNiN1oO16_J1K98Dta1KnH4hvNXcHqiRTdDZdA8k=s176-c-k-c0x00ffffff-no-rj", title: "[EN] 키192cm 아빠 어디가 준수X이종혁 부자 단독 공개 | 아침먹고 가2 EP.11", userName: "스튜디오 수제", viewCount: "119만 회"),
      ThumbModel(thumbImagePath: "https://i.ytimg.com/vi/F5MRiPZgOkM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLASLqpDYzJzMqSyY__LWNQECo7SXA", userImagePath: "https://yt3.ggpht.com/VovCAMdmNvWsAlDenNBzS6rDSUg636bPBKCA5EIup1o2Ny7DbUQlS88F4I7C-cqB5ckbiMr7=s48-c-k-c0x00ffffff-no-rj", title: "[최초공개] 송바오보다 의젓했던 푸바오 마지막 모습 (오열주의😭)", userName: "SBS TV동물농장x애니멀봐 공식 유튜브 채널입니다!", viewCount: "1.1만 회"),
      ThumbModel(thumbImagePath: "https://i.ytimg.com/vi/oKVYm8mIUdo/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAnQ23nxBPcVsSBh9Hi4ilr2Ogm4Q", userImagePath: "https://yt3.ggpht.com/KMO4AB7FMmpJrPejONrwsOA63BSJKudJaQ1K6qeRmBxQ0cpCPdcgrVjU2uCqHG7YasIRKqXaWw=s48-c-k-c0x00ffffff-no-nd-rj", title: "KISS OF LIFE (키스오브라이프) 'Midas Touch' Official Music Video", userName: "KISS OF LIFE", viewCount: "226만 회"),
      ThumbModel(thumbImagePath: "https://lh6.googleusercontent.com/proxy/3XYSO4gGwmTEn6PQQVQiHHXx1XhOq5wMDAj7AiDryemSQycBhLXJl4AXMzMtq6YGnkhX391aVvamqIgQQphQGoRJTdxWWpDZwnw4kKxL26vDETZQkGYtTAtIDFZqYO5-pMc", userImagePath: "https://static.aiffel.io/assets/img/landing-2023/logo-aiffel-sm-v1.0.png", title: "파이썬 기초부터 AI 앱 개발까지 탄탄하게", userName: "모두의 연구소 아이펠", viewCount: ""),
      ThumbModel(thumbImagePath: "https://i.ytimg.com/vi/DQd4KdI4-Aw/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCXteKHX9EPRWjEiald6mQ8EEpXGA", userImagePath: "https://yt3.ggpht.com/TDgG3gDEow_yMqaNQtrFjK4PNe8QN6xuFGBhAIm-zcP_ZrAc3QS_IwIVIYxudkRHMxuHu09n=s48-c-k-c0x00ffffff-no-rj", title: "KISS OF LIFE (키스오브라이프) - Midas Touch | 수트댄스 | Suit Dance | Performance | 4K", userName: "1theK Originals - 원더케이 오리지널", viewCount:"49만 회"),
      ThumbModel(thumbImagePath: "https://i.ytimg.com/an_webp/Heh80xExdq0/mqdefault_6s.webp?du=3000&sqp=CP22urAG&rs=AOn4CLCrsBenSWjANoByHsAqakxGCPYJQA", userImagePath: "https://yt3.ggpht.com/ihi8LdmSNfcp96-gaHBE1Av3-PLotF9rOhUxTy_pY-CeHYCAkDzE1ktxfe4gbhtYR0CIYjUPba0=s48-c-k-c0x00ffffff-no-rj", title: "야레야레~ 못 말리는 아가씨😎 오늘은 제가 모시겠습니다 | 집사 카페 | 워크맨2", userName: "워크맨-Workman", viewCount: "78만 회"),
    ];
  }
}